version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - microservices-network
    depends_on:
      - service1
      - service2

  service1:
    build: ./service1
    networks:
      - microservices-network
    # Убираем проброс портов наружу
    # ports:
    #   - "5000:5000"

  service2:
    build: ./service2
    networks:
      - microservices-network
    # Убираем проброс портов наружу
    # ports:
    #   - "5001:5001"

networks:
  microservices-network:
    driver: bridge